[book]
title = "Vyuh"
src = "src"
description = "Vyuh documentation"
authors = ["Vyuh contributors"]

[output.html]
site-url = "/"
additional-css = [
  "theme/vyuh.css",
]
git-repository-url = "https://github.com/vyuh-rs/vyuh"
edit-url-template = "https://github.com/vyuh-rs/vyuh/edit/main/docs/book/{path}"

[output.html.playground]
runnable = false
editable = false
copyable = true
