[book]
title = "Vyuh"
src = "src"
description = "Vyuh documentation"
authors = ["Vyuh contributors"]

[output.html]
site-url = "/vyuh/docs/"
additional-css = [
  "theme/vyuh.css",
]
git-repository-url = "https://github.com/vivsh/vyuh"
edit-url-template = "https://github.com/vivsh/vyuh/edit/main/docs/book/{path}"

[output.html.playground]
runnable = false
editable = false
copyable = true
